name: Greetings Workflow

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
  discussion:
    types: [created]
  fork:
    types: [created]
  

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send Welcome Message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ğŸ‘‹ Thank you for raising an issue! We appreciate your effort in helping us improve. 
            Our team will review it shortly. Stay tuned!
          pr-message: |
            ğŸ‰ Thank you for your contribution! Your pull request has been submitted successfully. 
            A maintainer will review it as soon as possible. We appreciate your support in making this project better!
          discussion-message: |
            ğŸ’¬ Thank you for starting a discussion! Your thoughts and questions help make this community stronger. 
            We will join the conversation soon!
          fork-message: |
            ğŸ´ Thank you for forking this repository! Weâ€™re excited to see how youâ€™ll build upon our work. Feel free to contribute back!

